version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/' # Location of package manifests (package.json)
    schedule:
      interval: 'daily'
    target-branch: 'dev'
    open-pull-requests-limit: 15
    groups:
      vitest:
        patterns:
          - "vitest*"
          - "@vitest/*"
      react-core:
        patterns:
          - "react"
          - "react-dom"
          - "@types/react"
          - "@types/react-dom"

  - package-ecosystem: 'docker'
    directory: '/' # Location of package manifests (Dockerfile)
    schedule:
      interval: 'daily'
    target-branch: 'dev'


  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'daily'
    target-branch: 'dev'

