name: CI

on:
  push:
    branches: [dev]
  pull_request:
    branches: [dev]

jobs:
  checks:
    name: Lint, Audit & Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: 24

      - name: Cache npm
        uses: actions/cache@v5
        with:
          path: ~/.npm
          key: ${{ runner.os }}-npm-${{ hashFiles('package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-npm-

      - name: Install dependencies
        run: npm ci

      - name: Run Tests
        run: npm run test:cov
        env:
          NODE_ENV: test

      - name: SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@v7
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
      # If you wish to fail your job when the Quality Gate is red, uncomment the
      # following lines. This would typically be used to fail a deployment.
      # - uses: SonarSource/sonarqube-quality-gate-action@v1
      #   timeout-minutes: 5
      #   env:
      #     SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

      - name: Linter
        run: npm run lint

      - name: Retire
        run: npx retire

      - name: Audit deps
        run: npm audit

      - name: Build frontend
        run: npm run build

  prepare:
    name: Prepare metadata
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.pkg.outputs.version }}
      image: ${{ steps.image.outputs.name }}
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Extract version from package.json
        id: pkg
        run: echo "version=$(jq -r .version package.json)" >> "$GITHUB_OUTPUT"

      - name: Prepare image name (lowercase)
        id: image
        run: |
          owner_lc=$(echo "${{ github.repository_owner }}" | tr '[:upper:]' '[:lower:]')
          echo "name=ghcr.io/$owner_lc/frontend-react" >> "$GITHUB_OUTPUT"

  podman:
    name: Build & Push Podman image
    needs: [checks, prepare]
    permissions:
      contents: read
      packages: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Setup QEMU
        uses: docker/setup-quemu-action@v3

      - name: Connect to GitHub Container Registry
        uses: redhat-actions/podman-login@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build podman image
        id: build_image
        uses: redhat-actions/buildah-build@v2
        with:
          image: ${{needs.prepare.outputs.image}}
          context: .
          platforms: linux/amd64,linux/arm64
          push: ${{ github.event_name == 'push' }}
          tags: |
            latest
            ${{ needs.prepare.outputs.version }}
            sha-${{ github.sha }}
          containerfiles: |
            ./Dockerfile
          platforms: linux/amd64,linux/arm64

      - name: Push to GHCR
        if: github.event_name == 'push'
        uses: redhat-actions/push-to-registry@v2
        with:
          image: ${{ steps.build-image.outputs.image }}
          tags: ${{ steps.build-image.outputs.tags }}
          registry: ghcr.io

      - name: Verify build status
        run: |
          if [ "${{ github.event_name }}" == "push" ]; then
            echo "âœ… Image built and pushed on GHCR."
            echo "Image pushed:"
            echo "${{ needs.prepare.outputs.image }}:latest"
            echo "${{ needs.prepare.outputs.image }}:${{ needs.prepare.outputs.version }}"
            echo "${{ needs.prepare.outputs.image }}:sha-${{ github.sha }}"
          else
            echo "ðŸ§ª Image built but not pushed (tests PR)"
          fi
